# Generated by Django 3.1.5 on 2021-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210305_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ImageField(null=True, upload_to='awards'),
        ),
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(to='users.Award'),
        ),
    ]
